### ISSUE TITLE
Read me file

### ISSUE THREAD

**Issue by Oscar8401** [Deidre-Festus/MVC-Garage-Application#3]
Create a read me file, which holds information about the functionality of the application.

**Comment by Oscar8401** [comment]
Start the main page.
Add some content (description about the functionality).

**Comment by Oscar8401** [comment]
I start to add content.
Try when you have time to add some description about the application.

**Comment by Deidre-Festus** [comment]
Completed few updates on Contacts and Home page.  More to follow

**Comment by Oscar8401** [comment]
I went throw what you had done, looks great thank you.  we can improve it a little bit more. but we discuss this on Monday, so we implement new things to make it looks better.

**Comment by Oscar8401** [comment]
I need your support on the README.md file (under master branch) we have this file which is the description that the user sees about the application and the functionality, I wrote it, it is good enough.
but I need you to go throw it again and check the English (spelling, writing..etc), just to have it as much professional as we can.

**Comment by Deidre-Festus** [comment]
I've reviewed the ReadMe.md file and made spelling and grammatical corrections.
