### ISSUE TITLE
Extend the data base

### ISSUE THREAD

**Issue by Oscar8401** [Deidre-Festus/MVC-Garage-Application#7]
extend the data base to produce more information on the tables, but not throw inserting new seeds. 
this will happened with for loop ++i.

**Comment by Deidre-Festus** [comment]
Complete.
Created for loops that increment Registration Number, but keeps all other vehicle details constant. eg. Now we have 10 red ferraris, each with a different reg number. See code for further details.
For now I've only added +-80 vehicles, but it can be adjusted to whatever number we decide upon.

**Comment by Oscar8401** [comment]
Looks great. Thank you
